### ISSUE TITLE
more Infos in README.md

### ISSUE THREAD

**Issue by aparcar** [libremesh/lime-ui-ng#1]
Could you please provide more details on how to use the new UI?
At least a starting point for some documentation.

**Comment by p4u** [comment]
Sorry but there is not yet an usable implementation. We are working on
it. The current packet only installs the basic components: lighttpd +
websockets + RPC-api

But the Web page based on JavaScript and the Android APP are still missing.

On 14/03/17 18:47, aparcar wrote:
> Could you please provide more details on how to use the new UI?
> At least a starting point for some documentation.
> 

-- 
./p4u

**Comment by nicopace** [comment]
Closing the issue since we are evaluating if this is the best way to go.
If reopening the repo, then the first thing to do would be to write a proper README.
Thanks @aparcar for noticing!
