### ISSUE TITLE
rename lime-ui-ng

### ISSUE THREAD

**Issue by FreifunkUFO** [libremesh/lime-ui-ng#2]
please rename to a better name.
"next-generation" isnt meaningful at all.
maybe luci4, luci4lime or lime-ui-2017?

**Comment by p4u** [comment]
It has nothing to do with LuCi and it's not based on Lua anymore. About using a year (2017) in the name of a software package, I don't see it as a good idea.

Changing the name now is a bit painful, there are already other software components that relay on that name. So I would not do it.

**Comment by FreifunkUFO** [comment]
is luci hanging on lua by default? so see luci2, which might have other concept.
a year within package-name isnt nice, but "next-generation" is even more worse.

for me its a name for a nice marketing gag or for catching new developers. but how to name the next try after that "next-generation" thing? should we have a look to marketing-professionals and name it "very next generation", "extra, super, ultra or xp"? :-(

i know that name is already in use for next-generation-libremesh. but its easier to change it now to a more common name than later.
"ng" could be the name of the development-brunch of packages, but should not appear in the name of packages.

all so, i even dont understand jow when naming the luci2-successor just "luci-ng". please also see olsr-ng http://www.imn.htwk-leipzig.de/~jkohlsdo/nsm/olsr-ng.pdf or openwrt-firmware-ng http://luci.subsignal.org/trac/browser/firmware-ng?rev=2207&order=name or the package freifunk-statistics-ng-digitemp-de-le  http://luci.subsignal.org/trac/browser/firmware/packages/global/freifunk-statistics-ng-digitemp-de-le?rev=1396&order=name

**Comment by nicoechaniz** [comment]
This repo will be deprecated once we finish moving away from orangerpc, so the name wont be relevant anymore.
