### ISSUE TITLE
Implement get_internet_status

### ISSUE THREAD

**Issue by nicoechaniz** [libremesh/lime-ui-ng#7]
Should return Internet connectivity status.

May differentiate IPv4 and IPv6 status returning a result with this structure:
{
"IPv4": "reachable",
"IPv6": "reachable"
}

Related to libremesh/lime-app#34

**Comment by gmarcos87** [comment]
I think a more granular structure can be expanded more easily in the future. If we have to add attributes or handle errors we can do it without breaking anything. Like:

```json
{
  "IPv4" : {
     "reachable" : true
  },
  "IPv6" : {
     "reachable" : true
  }
}
```
With others atributtes:
```json
{
  "IPv4": {
     "reachable" : true,
     "ip": "10.5.5.5"
  },
  "IPv6": {
     "reachable" : false,
     "error": {
         "code": 0,
         "msg": "Example error message"
     }
  }
}
```

I do not remember what limitation with objects and lists has Lua.
